---
spring:
  profiles:
    active: local

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  showSql: true
  formatSql: true
  hbm2ddlAuto: none

logging:
  config: classpath:logback-spring.xml
  level[io.swagger.models.parameters.AbstractSerializableParameter]: error
  level[org.springframework]: INFO

server:
  port: ${PORT:5000}

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://stockking.gq:5432/stocking 
      username: stocking
      password: stocking1234
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 3
  
logging:
  level[org.hibernate.type.descriptor.sql]: INFO
  
---
spring:
  profiles: develop
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://stockking.gq:5432/stocking?sslmode=disable
      username: stocking
      password: stocking1234
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 3
    
logging:
  level[org.hibernate.type.descriptor.sql]: INFO

---
spring:
  profiles: production
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://54.180.140.193:5432/stocking 
      username: stocking
      password: stocking1234
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 3
    
logging:
  level[org.hibernate.type.descriptor.sql]: INFO
  
server:
  port: ${PORT:80}
  