---
spring:
  profiles:
    active: local
    include: oauth

spring.cache.jcache.config: classpath:ehcache.xml

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  showSql: false
  formatSql: true
  hbm2ddlAuto: none

logging:
  config: classpath:logback-spring.xml
  level[io.swagger.models.parameters.AbstractSerializableParameter]: error
  level[org.springframework]: INFO
  level[org.springframework.web.client.RestTemplate]: DEBUG
  level[org.hibernate.SQL]: DEBUG

server:
  port: ${PORT:5000}

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://54.180.140.193:5432/stocking 
      username: stocking
      password: stocking1234
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 3
      
logging:
  config: classpath:logback-spring.xml
  level[io.swagger.models.parameters.AbstractSerializableParameter]: error
  level[org.springframework]: INFO
  level[org.springframework.web.client.RestTemplate]: DEBUG
  level[org.hibernate.SQL]: DEBUG
  level[org.hibernate.type.descriptor.sql.BasicBinder]: TRACE  
      
---
spring:
  profiles: develop
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://54.180.140.193:5432/stocking?sslmode=disable
      username: stocking
      password: stocking1234
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 3
    
---
spring:
  profiles: production
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://54.180.140.193:5432/stocking 
      username: stocking
      password: stocking1234
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 3
    
logging:
  level[org.springframework.web.client.RestTemplate]: INFO
  
server:
  port: ${PORT:8080}
  