---
spring:
  profiles:
    active: local
    include: oauth

spring.cache.jcache.config: classpath:ehcache.xml

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  showSql: true
  formatSql: true
  hbm2ddlAuto: none

logging:
  config: classpath:logback-spring.xml
  level[io.swagger.models.parameters.AbstractSerializableParameter]: error
  level[org.springframework]: INFO
  level[org.springframework.web.client.RestTemplate]: DEBUG
  
server:
  port: ${PORT:5000}

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://arjuna.db.elephantsql.com:5432/kfnzwjso
      username: kfnzwjso
      password: PN6khtXWIbRT_aeYwnMqSKFx81C8637B
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 3
  
logging:
  level[org.hibernate.type.descriptor.sql]: INFO
  
---
spring:
  profiles: develop
  datasource:
    hikari:
      jdbc-url: ${STOCKING_JDBC_URL}
      username: ${STOCKING_USER}
      password: ${STOCKING_PASSWORD}
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 3
    
logging:
  level[org.hibernate.type.descriptor.sql]: INFO

---
spring:
  profiles: production
  datasource:
    hikari:
      jdbc-url: ${STOCKING_JDBC_URL}
      username: ${STOCKING_USER}
      password: ${STOCKING_PASSWORD}
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 10
    
logging:
  level[org.hibernate.type.descriptor.sql]: INFO
  
server:
  port: ${PORT:8443}
  ssl:
    key-store: /home/ubuntu/api/keystore.p12
    key-store-type: PKCS12    
    key-store-password: stocking1234
  